window.QUESTION_BANKS = window.QUESTION_BANKS || {};
window.QUESTION_BANKS["fisica"] = {
  label: "Física", icon: "⚡",
  questions: [
    { text: "Según la Ley de Ohm, si R = 10 Ω e I = 2 A, ¿cuál es el voltaje?", options: ["20 V","5 V","12 V","0.2 V"], correct: 0 },
    { text: "Dos resistencias de 4 Ω y 6 Ω están en serie. ¿Cuál es la resistencia total?", options: ["2.4 Ω","10 Ω","5 Ω","24 Ω"], correct: 1 },
    { text: "Dos resistencias de 6 Ω conectadas en paralelo equivalen a:", options: ["12 Ω","3 Ω","6 Ω","1 Ω"], correct: 1 },
    { text: "¿Cuál es la potencia disipada por una resistencia de 5 Ω con una corriente de 4 A?", options: ["20 W","80 W","0.8 W","100 W"], correct: 1 },
    { text: "La primera Ley de Kirchhoff (ley de nodos) establece que:", options: ["La suma de voltajes en una malla cerrada es cero","La suma de corrientes que entran a un nodo es igual a las que salen","La corriente es proporcional a la resistencia","La potencia es el producto de voltaje por corriente"], correct: 1 },
    { text: "La segunda Ley de Kirchhoff (ley de mallas) establece que:", options: ["La corriente se divide en los nodos","La suma algebraica de voltajes en una malla cerrada es igual a cero","La resistencia total en paralelo es menor que cualquiera de ellas","La energía no se crea ni se destruye"], correct: 1 },
    { text: "Un condensador (capacitor) almacena energía en forma de:", options: ["Energía cinética","Campo eléctrico","Campo magnético","Energía calorífica"], correct: 1 },
    { text: "La capacitancia se mide en:", options: ["Ohmios","Voltios","Faradios","Henrios"], correct: 2 },
    { text: "La energía almacenada en un condensador de capacitancia C cargado a voltaje V es:", options: ["E = CV","E = C²V","E = ½CV²","E = CV²"], correct: 2 },
    { text: "En un circuito con batería de 9 V y resistencia de 3 Ω, la corriente es:", options: ["3 A","27 A","0.33 A","6 A"], correct: 0 },
    { text: "Si P = 60 W y V = 12 V, la corriente que circula es:", options: ["720 A","48 A","5 A","0.2 A"], correct: 2 },
    { text: "Los condensadores en paralelo se suman como:", options: ["1/C_total = 1/C1 + 1/C2","C_total = C1 + C2","C_total = C1 × C2","C_total = C1 - C2"], correct: 1 },
    { text: "La reactancia inductiva de una bobina de inductancia L a frecuencia f es:", options: ["XL = 2πfL","XL = L/2πf","XL = 1/2πfL","XL = 2πf/L"], correct: 0 },
    { text: "La reactancia capacitiva de un condensador de capacitancia C a frecuencia f es:", options: ["XC = 2πfC","XC = C/2πf","XC = 1/(2πfC)","XC = 2πf/C"], correct: 2 },
    { text: "La impedancia de un circuito RLC en serie es:", options: ["Z = R + XL + XC","Z = √(R² + (XL − XC)²)","Z = R × (XL + XC)","Z = R² + (XL − XC)²"], correct: 1 },
    { text: "¿Qué ocurre en resonancia en un circuito RLC?", options: ["XL = 0","XC = 0","XL = XC y la impedancia es mínima (Z = R)","La resistencia se anula"], correct: 2 },
    { text: "La velocidad de una onda se relaciona con su frecuencia y longitud de onda mediante:", options: ["v = λ + f","v = λ · f","v = f / λ","v = λ / f"], correct: 1 },
    { text: "El período T y la frecuencia f están relacionados por:", options: ["T = f²","T = f","T = 1/f","T = 2πf"], correct: 2 },
    { text: "Las ondas transversales tienen su desplazamiento:", options: ["Paralelo a la dirección de propagación","Perpendicular a la dirección de propagación","En espiral alrededor del eje","En todas las direcciones a la vez"], correct: 1 },
    { text: "El sonido es un ejemplo de onda:", options: ["Transversal electromagnética","Transversal mecánica","Longitudinal mecánica","Longitudinal electromagnética"], correct: 2 },
    { text: "El principio de superposición establece que cuando dos ondas se encuentran:", options: ["La mayor destruye a la menor","Se suman algebraicamente en el punto de encuentro","Se multiplican sus amplitudes","La frecuencia resultante es la media de ambas"], correct: 1 },
    { text: "La interferencia constructiva ocurre cuando dos ondas se superponen:", options: ["Con desfase de media longitud de onda","En fase (desfase de 0 o múltiplo entero de λ)","Con amplitudes muy diferentes","En sentidos opuestos de propagación"], correct: 1 },
    { text: "La difracción es el fenómeno por el cual las ondas:", options: ["Cambian de velocidad al cambiar de medio","Se doblan al pasar por una abertura u obstáculo","Se reflejan en superficies lisas","Se descomponen en sus frecuencias componentes"], correct: 1 },
    { text: "El efecto Doppler describe la variación de:", options: ["La amplitud de la onda por movimiento relativo","La frecuencia percibida por movimiento relativo entre fuente y observador","La velocidad de la onda en distintos medios","La longitud de onda en medios dispersivos"], correct: 1 },
    { text: "La velocidad del sonido en el aire a 20 °C es aproximadamente:", options: ["150 m/s","343 m/s","1500 m/s","3×10⁸ m/s"], correct: 1 },
    { text: "La velocidad de la luz en el vacío es:", options: ["3×10⁶ m/s","3×10⁸ m/s","3×10¹⁰ m/s","3×10⁴ m/s"], correct: 1 },
    { text: "Si una onda tiene frecuencia de 170 Hz y velocidad de 340 m/s, su longitud de onda es:", options: ["2 m","0.5 m","4 m","57800 m"], correct: 0 },
    { text: "El rango de frecuencias audible para el oído humano es aproximadamente:", options: ["0 – 200 Hz","20 Hz – 20 000 Hz","200 Hz – 200 000 Hz","1 MHz – 10 MHz"], correct: 1 },
    { text: "El ultrasonido tiene frecuencias:", options: ["Menores de 20 Hz","Entre 20 Hz y 20 kHz","Mayores de 20 000 Hz","Iguales a la frecuencia de resonancia del oído"], correct: 2 },
    { text: "La intensidad sonora se mide en:", options: ["Hercios (Hz)","Metros por segundo (m/s)","Decibelios (dB)","Pascales al cuadrado (Pa²)"], correct: 2 },
    { text: "La Ley de reflexión establece que:", options: ["El ángulo de incidencia es el doble del de reflexión","El ángulo de incidencia es igual al ángulo de reflexión","El rayo reflejado cambia de medio","El rayo reflejado tiene menor frecuencia"], correct: 1 },
    { text: "La refracción ocurre porque la luz:", options: ["Rebota en la superficie del nuevo medio","Cambia de velocidad al pasar de un medio a otro","Se absorbe y re-emite con diferente color","Se difracta en la interfase"], correct: 1 },
    { text: "El índice de refracción n de un medio se define como:", options: ["n = v/c","n = c/v","n = λ · f","n = c · v"], correct: 1 },
    { text: "Una lente convergente (convexa) produce en objetos lejanos imágenes:", options: ["Virtuales y derechas","Reales, invertidas y en el foco","Virtuales e invertidas","Reales y del mismo tamaño siempre"], correct: 1 },
    { text: "El fenómeno del arcoíris se produce por:", options: ["Difracción de la luz en las nubes","Interferencia de ondas de radio","Reflexión interna y dispersión de la luz en gotas de agua","Polarización de la luz solar"], correct: 2 },
    { text: "La Ley de Coulomb indica que la fuerza entre dos cargas eléctricas es:", options: ["Inversamente proporcional al cuadrado de la distancia y proporcional al producto de las cargas","Proporcional a la distancia","Independiente de las cargas","Inversamente proporcional a la distancia"], correct: 0 },
    { text: "El campo eléctrico se mide en:", options: ["Coulombs (C)","N/C o equivalentemente V/m","Faradios (F)","Tesla (T)"], correct: 1 },
    { text: "Las líneas de campo eléctrico salen de:", options: ["Cargas negativas hacia positivas","Cargas positivas y llegan a cargas negativas","Puntos de alta resistencia","La tierra hacia las cargas"], correct: 1 },
    { text: "El voltaje se mide con un instrumento llamado:", options: ["Amperímetro (en serie)","Galvanómetro","Voltímetro (en paralelo)","Ohmímetro"], correct: 2 },
    { text: "El efecto Joule describe que al circular corriente por un conductor:", options: ["Se genera un campo magnético sin pérdidas","Se produce calor proporcional a I²R","La resistencia disminuye con el tiempo","El conductor se carga eléctricamente"], correct: 1 },
    { text: "Una onda de frecuencia 440 Hz tiene un período de:", options: ["440 s","0.00227 s (≈ 2.27 ms)","22 ms","4.4 s"], correct: 1 },
    { text: "El principio de Huygens establece que:", options: ["La velocidad de la luz es constante en el vacío","Cada punto de un frente de onda actúa como fuente de ondas secundarias","Las ondas no pueden propagarse en el vacío","La energía de una onda es proporcional a su frecuencia al cuadrado"], correct: 1 },
    { text: "La potencia reactiva en un circuito de CA se mide en:", options: ["Vatios (W)","Voltamperios reactivos (VAR)","Julios (J)","Faradios (F)"], correct: 1 },
    { text: "Un espejo plano forma imágenes:", options: ["Reales, invertidas y del mismo tamaño","Virtuales, derechas y del mismo tamaño","Reales y aumentadas","Virtuales e invertidas"], correct: 1 },
    { text: "La dispersión de la luz blanca en un prisma ocurre porque:", options: ["Los colores tienen la misma velocidad en el vidrio","El índice de refracción depende de la longitud de onda del color","Solo el rojo se refracta en el vidrio","La amplitud de cada color es diferente"], correct: 1 },
    { text: "El rango de longitudes de onda de la luz visible es aproximadamente:", options: ["10 – 100 nm","380 – 750 nm","1 mm – 10 mm","1 μm – 1 cm"], correct: 1 },
    { text: "La resonancia en un sistema oscilante ocurre cuando:", options: ["La frecuencia de excitación es muy pequeña","La frecuencia de excitación coincide con la frecuencia natural del sistema","La amplitud es igual a cero","La resistencia del circuito es infinita"], correct: 1 },
    { text: "Las ondas electromagnéticas, a diferencia de las mecánicas:", options: ["Solo se propagan en sólidos","No necesitan un medio material para propagarse","Viajan más lento que el sonido","Son siempre longitudinales"], correct: 1 },
    { text: "¿Cuánta energía (en Julios) almacena un condensador de 200 μF cargado a 50 V?", options: ["0.25 J","0.5 J","5 J","250 J"], correct: 0 },
    { text: "El efecto fotoeléctrico, explicado por Einstein, demuestra que la luz se comporta como:", options: ["Onda transversal pura","Partículas llamadas fotones","Onda longitudinal","Plasma electromagnético"], correct: 1 },
    { text: "Tres resistencias de 3 Ω, 6 Ω y 6 Ω están en paralelo. ¿Cuál es la resistencia equivalente?", options: ["15 Ω","1.5 Ω","5 Ω","3 Ω"], correct: 1 }
  ]
};
