window.QUESTION_BANKS = window.QUESTION_BANKS || {};
window.QUESTION_BANKS["frances"] = {
  label: "Français", icon: "🇫🇷",
  questions: [
    { text: "Conjugue correctement : 'Nous ___ (aller) au cinéma ce soir.'", options: ["allons","allez","vont","allaient"], correct: 0 },
    { text: "Quelle est la conjugaison correcte ? 'Il ___ (faire) beau aujourd'hui.'", options: ["fait","fais","faisons","ferait"], correct: 0 },
    { text: "Complète avec le passé composé : 'Elle ___ (partir) hier matin.'", options: ["est partie","a parti","était partie","part"], correct: 0 },
    { text: "¿Cuál es el auxiliar correcto? 'Ils ___ (venir) à la fête.'", options: ["sont venus","ont venus","étaient venus","venaient"], correct: 0 },
    { text: "Elige el imparfait correcto: 'Quand j'étais petit, je ___ (jouer) tous les jours.'", options: ["jouais","joué","ai joué","jouerai"], correct: 0 },
    { text: "¿Cuándo se usa el imparfait? Se usa para:", options: ["Acciones habituales o descriptivas en el pasado","Acciones puntuales completadas en el pasado","Acciones futuras hipotéticas","Órdenes y mandatos"], correct: 0 },
    { text: "Forme le plus-que-parfait : 'Quand il est arrivé, elle ___ déjà (partir).'", options: ["était déjà partie","a déjà parti","avait déjà partis","est déjà partie"], correct: 0 },
    { text: "Conjugue au futur simple : 'Demain, nous ___ (finir) le projet.'", options: ["finirons","finissons","finirions","avons fini"], correct: 0 },
    { text: "Elige el conditionnel présent: 'Si j'avais de l'argent, je ___ (voyager).'", options: ["voyagerais","voyagerai","voyageais","ai voyagé"], correct: 0 },
    { text: "¿Cuál es el subjonctif correcto? 'Il faut que tu ___ (être) à l'heure.'", options: ["sois","es","étais","seras"], correct: 0 },
    { text: "¿Cuándo se usa el subjonctif?", options: ["Después de expresiones de duda, deseo, emoción o necesidad","Para describir acciones pasadas completadas","Para acciones habituales en el presente","Para expresar acciones futuras ciertas"], correct: 0 },
    { text: "Forma la negación correcta para 'Je mange':", options: ["Je ne mange pas","Je pas mange","Je mange ne pas","Ne je mange pas"], correct: 0 },
    { text: "Elige el pronom relatif correcto: 'Le livre ___ j'ai lu est excellent.'", options: ["que","qui","dont","où"], correct: 0 },
    { text: "¿Cuál es el acuerdo correcto del participio? 'La robe qu'elle ___ (acheter) est belle.'", options: ["a achetée","a acheté","est achetée","avait acheté"], correct: 0 },
    { text: "¿Qué significa la expresión 'il s'agit de'?", options: ["Se trata de","Se habla de manera informal","Es necesario que","Se dice que"], correct: 0 },
    { text: "¿Cómo se traduce 'Quand même' al español?", options: ["De todos modos / Sin embargo","Cuando mismo","Cuándo y cómo","En cuanto"], correct: 0 },
    { text: "Complète avec le bon pronom: '___ est ton livre préféré?'", options: ["Quel","Quelle","Quels","Quelles"], correct: 0 },
    { text: "¿Cuál es la forma correcta? 'Je veux que vous ___ (venir).'", options: ["veniez","venez","viendrez","êtes venus"], correct: 0 },
    { text: "'Bien que' se construye siempre con:", options: ["Le subjonctif","L'indicatif présent","Le conditionnel","L'infinitif"], correct: 0 },
    { text: "¿Qué significa 'se débrouiller'?", options: ["Arreglárselas / ingeniárselas","Perderse","Darse prisa","Equivocarse"], correct: 0 },
    { text: "Conjugue au passé simple: 'Il ___ (parler) à son ami.' (littéraire)", options: ["parla","a parlé","parlait","parlera"], correct: 0 },
    { text: "¿Cuál es el femenino de 'acteur'?", options: ["actrice","acteure","actèse","acteuse"], correct: 0 },
    { text: "La phrase 'Je l'ai vu hier' contient le pronom complément d'objet direct:", options: ["l'","je","ai","hier"], correct: 0 },
    { text: "Elige la preposición correcta: 'Je vais ___ Paris.'", options: ["à","en","dans","de"], correct: 0 },
    { text: "Para expresar duración continua en el presente se usa:", options: ["Présent de l'indicatif + depuis","Passé composé + depuis","Imparfait + depuis","Futur + depuis"], correct: 0 },
    { text: "'N'importe qui' significa:", options: ["Cualquiera","Nadie","Alguien importante","No importa quién — ambas son correctas"], correct: 0 },
    { text: "La forma correcta del gérondif de 'manger' es:", options: ["en mangeant","en mange","mangeant","en mangé"], correct: 0 },
    { text: "¿Qué expresa el mode conditionnel passé? 'J'aurais pu venir.'", options: ["Una acción hipotética no realizada en el pasado","Una orden pasada","Un hecho cierto del pasado","Un deseo presente"], correct: 0 },
    { text: "¿Cuál es la negación de 'Je mange toujours'?", options: ["Je ne mange jamais","Je ne mange pas toujours","Je mange toujours pas","Je ne toujours mange"], correct: 0 },
    { text: "Le pronom 'y' remplace généralement:", options: ["Un lieu ou un complément introduit par 'à'","Une personne féminine","Un adjectif qualificatif","Un nom au pluriel"], correct: 0 },
    { text: "Le pronom 'en' remplace:", options: ["Un complément introduit por 'de' o una cantidad","Un lugar específico","Un pronombre personal tónico","Un adverbio de tiempo"], correct: 0 },
    { text: "¿Cuál es el antónimo de 'rapide'?", options: ["lent","fort","grand","dur"], correct: 0 },
    { text: "Complète: 'Plus on travaille, ___ on réussit.'", options: ["plus","moins","mieux","autant"], correct: 0 },
    { text: "'Avoir lieu' significa:", options: ["Tener lugar / ocurrir","Tener un lugar físico","Llegar a tiempo","Ganar un lugar"], correct: 0 },
    { text: "¿Cuál es la bonne orthographe? 'Il faut ___ (savoir) la vérité.'", options: ["savoir","sache","sait","su"], correct: 0 },
    { text: "La locución 'à moins que' se construye con:", options: ["Le subjonctif","L'indicatif","Le conditionnel","L'infinitif"], correct: 0 },
    { text: "¿Qué significa 'se rendre compte'?", options: ["Darse cuenta","Rendirse","Volver a casa","Dar cuentas"], correct: 0 },
    { text: "En la phrase passive 'Le gâteau est mangé par les enfants', l'agent est:", options: ["les enfants","le gâteau","est","mangé"], correct: 0 },
    { text: "Complète au futur proche: 'Nous ___ (partir) bientôt.'", options: ["allons partir","partons","sommes partis","irons partir"], correct: 0 },
    { text: "El discurso indirecto de 'Il dit: «Je suis fatigué»' es:", options: ["Il dit qu'il est fatigué","Il dit qu'il était fatigué","Il dit que je suis fatigué","Il dit il est fatigué"], correct: 0 },
    { text: "¿Cuál es el superlatif de 'bon'?", options: ["le meilleur","le plus bon","le très bon","le mieux bon"], correct: 0 },
    { text: "¿Cuándo se usa 'depuis' vs. 'pendant'?", options: ["'Depuis' para duración desde un punto en el pasado hasta ahora; 'pendant' para duración delimitada","Son completamente intercambiables","'Pendant' siempre con presente; 'depuis' siempre con pasado","'Depuis' para el futuro; 'pendant' para el pasado"], correct: 0 },
    { text: "La forma correcta es: 'Donne-___ le livre!'", options: ["moi","me","je","mon"], correct: 0 },
    { text: "¿Qué significa 'tant que'?", options: ["Mientras / en tanto que","Tan pronto como","Aunque","A menos que"], correct: 0 },
    { text: "Complète: 'Il ___ (falloir) que tu partes maintenant.'", options: ["faut","fallait","faudra","faille"], correct: 0 },
    { text: "L'accord du participe passé avec 'avoir' se fait avec:", options: ["Le sujet du verbe","Le complément d'objet direct placé avant le verbe","Toujours avec le verbe","Le complément d'objet indirect"], correct: 1 },
    { text: "¿Cuál de estas palabras es un adverbe de manière?", options: ["rapidement","souvent","demain","beaucoup"], correct: 0 },
    { text: "Le comparatif de supériorité de 'grand' est:", options: ["plus grand","le plus grand","grand que","très grand"], correct: 0 },
    { text: "Complète: 'Je cherche un appartement ___ soit calme.' (relatif + subjonctif)", options: ["qui","que","dont","où"], correct: 0 },
    { text: "¿Qué significa 'à condition que'?", options: ["Con la condición de que (+ subjonctif)","A pesar de que","En cuanto","Antes de que"], correct: 0 }
  ]
};
