window.QUESTION_BANKS = window.QUESTION_BANKS || {};
window.QUESTION_BANKS["literatura"] = {
  label: "Literatura", icon: "📚",
  questions: [
    { text: "¿Quién es el autor de 'El ingenioso hidalgo Don Quijote de la Mancha'?", options: ["Miguel de Cervantes","Lope de Vega","Francisco de Quevedo","Garcilaso de la Vega"], correct: 0 },
    { text: "¿En qué año se publicó la primera parte del Quijote?", options: ["1492","1616","1605","1580"], correct: 2 },
    { text: "¿Quién escribió 'Fuenteovejuna'?", options: ["Calderón de la Barca","Lope de Vega","Tirso de Molina","Quevedo"], correct: 1 },
    { text: "'La vida es sueño' pertenece a:", options: ["Lope de Vega","Francisco de Quevedo","Calderón de la Barca","Góngora"], correct: 2 },
    { text: "Francisco de Quevedo es representante del:", options: ["Culteranismo","Naturalismo","Conceptismo","Modernismo"], correct: 2 },
    { text: "Luis de Góngora es representante del:", options: ["Culteranismo","Conceptismo","Romanticismo","Realismo"], correct: 0 },
    { text: "¿A qué género pertenece el 'Lazarillo de Tormes'?", options: ["Épica","Novela picaresca","Drama barroco","Lírica renacentista"], correct: 1 },
    { text: "La Generación del 98 surgió como respuesta a:", options: ["La Revolución Industrial","La Primera Guerra Mundial","La pérdida de las últimas colonias españolas","La Restauración borbónica"], correct: 2 },
    { text: "Federico García Lorca pertenece a la:", options: ["Generación del 98","Generación del 27","Generación del 14","Modernismo hispanoamericano"], correct: 1 },
    { text: "¿Quién escribió 'Romancero gitano'?", options: ["Rafael Alberti","Antonio Machado","Federico García Lorca","Luis Cernuda"], correct: 2 },
    { text: "¿Quién es el autor de 'Niebla'?", options: ["Pío Baroja","Miguel de Unamuno","Azorín","Ramón del Valle-Inclán"], correct: 1 },
    { text: "¿Cuántos versos tiene un soneto?", options: ["12","14","16","10"], correct: 1 },
    { text: "El romance clásico se caracteriza por versos de:", options: ["11 sílabas con rima consonante","8 sílabas con rima asonante en los pares","8 sílabas con rima consonante en todos","6 sílabas con rima alterna"], correct: 1 },
    { text: "¿Quién escribió 'Don Juan Tenorio'?", options: ["Gustavo Adolfo Bécquer","Mariano José de Larra","Duque de Rivas","José Zorrilla"], correct: 3 },
    { text: "'La Regenta' fue escrita por:", options: ["Benito Pérez Galdós","Leopoldo Alas 'Clarín'","Emilia Pardo Bazán","Juan Valera"], correct: 1 },
    { text: "El Naturalismo literario está asociado principalmente con:", options: ["Victor Hugo","Émile Zola","Charles Baudelaire","Gustave Flaubert"], correct: 1 },
    { text: "El 'Cantar de Mio Cid' pertenece a la literatura:", options: ["Renacentista","Barroca","Medieval","Romántica"], correct: 2 },
    { text: "¿Quién escribió 'Platero y yo'?", options: ["Antonio Machado","Rubén Darío","Miguel de Unamuno","Juan Ramón Jiménez"], correct: 3 },
    { text: "El Modernismo hispanoamericano fue iniciado por:", options: ["César Vallejo","Jorge Luis Borges","Rubén Darío","Pablo Neruda"], correct: 2 },
    { text: "¿Cuál es la obra principal de Garcilaso de la Vega?", options: ["Las Coplas","Églogas y Sonetos","Cantigas de amor","Romances fronterizos"], correct: 1 },
    { text: "Las 'Coplas a la muerte de su padre' fueron escritas por:", options: ["Jorge Manrique","Juan de Mena","Marqués de Santillana","Alfonso X"], correct: 0 },
    { text: "El Realismo literario del siglo XIX se caracteriza por:", options: ["La idealización de la naturaleza","La exaltación del yo romántico","La representación objetiva de la realidad social","El uso de simbolismos y metáforas herméticas"], correct: 2 },
    { text: "¿Qué es un bildungsroman?", options: ["Novela de formación o aprendizaje del protagonista","Novela histórica medieval","Poema épico de héroes nacionales","Obra de teatro con final trágico"], correct: 0 },
    { text: "'Cien años de soledad' pertenece al movimiento literario llamado:", options: ["Realismo mágico","Surrealismo","Costumbrismo","Naturalismo"], correct: 0 },
    { text: "Gabriel García Márquez era de nacionalidad:", options: ["Mexicana","Argentina","Colombiana","Venezolana"], correct: 2 },
    { text: "El 'stream of consciousness' (flujo de conciencia) es una técnica narrativa asociada a:", options: ["Stendhal y Balzac","Virginia Woolf y James Joyce","Cervantes y Quevedo","Zola y Flaubert"], correct: 1 },
    { text: "La silva es una estrofa que combina versos de:", options: ["14 y 7 sílabas","11 y 7 sílabas","8 y 6 sílabas","11 y 5 sílabas"], correct: 1 },
    { text: "¿Qué movimiento representa 'Las flores del mal' de Baudelaire?", options: ["Romanticismo tardío / Simbolismo","Realismo","Naturalismo","Neoclasicismo"], correct: 0 },
    { text: "El narrador omnisciente es aquel que:", options: ["Participa como personaje de la historia","Conoce los pensamientos y hechos de todos los personajes","Solo narra lo que percibe desde fuera","Cuenta la historia en segunda persona"], correct: 1 },
    { text: "¿Cuál es el recurso literario que consiste en atribuir cualidades humanas a cosas inanimadas?", options: ["Metáfora","Hipérbole","Personificación o prosopopeya","Sinécdoque"], correct: 2 },
    { text: "La antítesis es la contraposición de:", options: ["Dos sonidos similares","Dos ideas contrarias","Dos personajes opuestos","Dos géneros literarios"], correct: 1 },
    { text: "¿Cuál de estos escritores pertenece a la Generación del 98?", options: ["Rubén Darío","Federico García Lorca","Miguel de Unamuno","Rafael Alberti"], correct: 2 },
    { text: "El teatro del absurdo está representado por obras como 'Esperando a Godot', escrita por:", options: ["Eugène Ionesco","Jean-Paul Sartre","Samuel Beckett","Albert Camus"], correct: 2 },
    { text: "El alejandrino es un verso de:", options: ["11 sílabas","12 sílabas","14 sílabas","8 sílabas"], correct: 2 },
    { text: "¿Cuál es la figura retórica del siguiente verso: 'En el principio era el Verbo'?", options: ["Hipérbaton","Anáfora","Alusión bíblica o cita","Quiasmo"], correct: 2 },
    { text: "La obra 'La casa de Bernarda Alba' de García Lorca es una tragedia que trata sobre:", options: ["La Guerra Civil Española","La opresión, el honor y la represión femenina en la España rural","El exilio republicano","La dictadura franquista"], correct: 1 },
    { text: "¿Quién escribió 'Rayuela'?", options: ["Mario Vargas Llosa","Julio Cortázar","Carlos Fuentes","Alejo Carpentier"], correct: 1 },
    { text: "El Siglo de Oro español abarca aproximadamente:", options: ["Siglos XIII-XIV","Siglos XVI-XVII","Siglos XVIII-XIX","Siglos XIV-XV"], correct: 1 },
    { text: "La 'Celestina' o 'Tragicomedia de Calisto y Melibea' fue escrita por:", options: ["Cervantes","Juan del Encina","Fernando de Rojas","Lope de Rueda"], correct: 2 },
    { text: "¿Qué es la rima asonante?", options: ["Coincidencia de todos los sonidos finales del verso","Coincidencia solo de los sonidos vocálicos desde la última vocal tónica","Ausencia total de rima","Rima que se produce cada tres versos"], correct: 1 },
    { text: "El soliloquio en teatro es:", options: ["Un diálogo entre dos personajes","Un discurso de un personaje que habla solo en escena","La acotación escénica del autor","Un monólogo narrado fuera del escenario"], correct: 1 },
    { text: "El escritor Jorge Luis Borges era de nacionalidad:", options: ["Uruguaya","Chilena","Argentina","Peruana"], correct: 2 },
    { text: "¿A qué género pertenece la 'Ilíada' de Homero?", options: ["Lírica","Épica","Drama","Sátira"], correct: 1 },
    { text: "La 'Oda a la alegría' de Schiller fue incorporada musicalmente por:", options: ["Mozart","Brahms","Beethoven","Schubert"], correct: 2 },
    { text: "El modernismo literario en España tiene como figura central a:", options: ["Antonio Machado","Juan Ramón Jiménez","Unamuno","Baroja"], correct: 1 },
    { text: "¿Cuál es la obra de Dante Alighieri que describe un viaje por el infierno, el purgatorio y el paraíso?", options: ["La Eneida","La Divina Comedia","El Decamerón","El cancionero"], correct: 1 },
    { text: "La novela epistolar es aquella que:", options: ["Narra hechos históricos documentados","Está escrita en forma de cartas o correspondencia","Es una autobiografía ficticia","Usa el monólogo interior exclusivamente"], correct: 1 },
    { text: "El hipérbaton es la figura retórica que consiste en:", options: ["Exagerar una idea hasta lo absurdo","Alterar el orden sintáctico normal","Repetir una palabra al inicio de varios versos","Comparar dos realidades con nexo"], correct: 1 },
    { text: "'La metamorfosis' de Franz Kafka pertenece al género:", options: ["Realismo costumbrista","Narrativa fantástica / literatura del absurdo","Novela histórica","Novela picaresca"], correct: 1 },
    { text: "¿Quién escribió 'Pedro Páramo'?", options: ["Carlos Fuentes","Octavio Paz","Juan Rulfo","José Revueltas"], correct: 2 }
  ]
};
