window.QUESTION_BANKS = window.QUESTION_BANKS || {};
window.QUESTION_BANKS["matematicas"] = {
  label: "Matemáticas", icon: "📐",
  questions: [
    { text: "¿Cuál es el resultado de: 2 + 3 × 4 − 8 ÷ 2?", options: ["10","8","6","12"], correct: 0 },
    { text: "¿Cuánto es: (5 + 3)² ÷ 4 − 6 × 2?", options: ["0","4","−4","8"], correct: 0 },
    { text: "¿Resultado de: 3 × (2 + 5) − 4² + 10 ÷ 2?", options: ["9","12","10","6"], correct: 0 },
    { text: "¿Cuánto es el 35% de 240?", options: ["84","96","72","80"], correct: 0 },
    { text: "Simplifica la fracción 48/72:", options: ["2/3","3/4","4/6","5/7"], correct: 0 },
    { text: "Si 3x − 7 = 14, ¿cuánto vale x?", options: ["7","9","5","3"], correct: 0 },
    { text: "Factoriza: x² − 9", options: ["(x − 3)(x + 3)","(x − 9)(x + 1)","(x + 3)²","(x − 3)²"], correct: 0 },
    { text: "¿Cuáles son las raíces de x² − 5x + 6 = 0?", options: ["x = 2 y x = 3","x = 1 y x = 6","x = −2 y x = −3","x = 5 y x = 1"], correct: 0 },
    { text: "El área de un triángulo con base 10 cm y altura 6 cm es:", options: ["30 cm²","60 cm²","20 cm²","15 cm²"], correct: 0 },
    { text: "¿Cuánto mide la hipotenusa de un triángulo rectángulo con catetos de 6 y 8?", options: ["10","14","12","9"], correct: 0 },
    { text: "¿Cuál es el límite de (x² − 1)/(x − 1) cuando x → 1?", options: ["2","1","0","Indefinido"], correct: 0 },
    { text: "¿Cuánto vale lím(x→∞) de (3x² + 2x) / (x² − 5)?", options: ["3","2","0","∞"], correct: 0 },
    { text: "¿Cuál es la derivada de f(x) = 5x³ − 4x² + 7x − 2?", options: ["15x² − 8x + 7","5x² − 4x + 7","15x² − 4x + 7","15x³ − 8x + 7"], correct: 0 },
    { text: "Usando la regla de la cadena, ¿cuál es la derivada de f(x) = (3x + 1)⁴?", options: ["12(3x + 1)³","4(3x + 1)³","3(3x + 1)⁴","4(3x)³"], correct: 0 },
    { text: "¿Cuál es la derivada de f(x) = sen(x) · cos(x)?", options: ["cos(2x)","−sen(2x)","cos²(x) − sen²(x)","2 sen(x) cos(x)"], correct: 0 },
    { text: "¿Cuánto vale sen(30°)?", options: ["√3/2","1/2","1","√2/2"], correct: 1 },
    { text: "¿Cuánto vale cos(60°)?", options: ["√3/2","0","1/2","1"], correct: 2 },
    { text: "La identidad trigonométrica fundamental es:", options: ["sen²(x) + cos(x) = 1","sen(x) + cos(x) = 1","sen²(x) + cos²(x) = 1","sen²(x) − cos²(x) = 0"], correct: 2 },
    { text: "¿Cuánto es tan(45°)?", options: ["0","√3","1/2","1"], correct: 3 },
    { text: "La ley de los senos establece que:", options: ["a/sen(A) = b/sen(B) = c/sen(C)","a · sen(A) = b · sen(B)","a² = b² + c² − 2bc·cos(A)","sen(A)/a = a/sen(A)"], correct: 0 },
    { text: "∫ 2x dx es igual a:", options: ["2","x² + C","x + C","2x² + C"], correct: 1 },
    { text: "∫ cos(x) dx es igual a:", options: ["−sen(x) + C","sen(x) + C","−cos(x) + C","tan(x) + C"], correct: 1 },
    { text: "¿Cuánto es ∫₀¹ x² dx?", options: ["1","1/2","1/3","2"], correct: 2 },
    { text: "El número de combinaciones de 5 elementos tomados de 2 en 2 (C(5,2)) es:", options: ["20","10","5","25"], correct: 1 },
    { text: "¿Cuántos resultados posibles hay al lanzar dos dados?", options: ["12","24","36","6"], correct: 2 },
    { text: "La probabilidad de obtener cara al lanzar una moneda justa es:", options: ["1/4","1/3","1","1/2"], correct: 3 },
    { text: "La media aritmética de {2, 4, 6, 8, 10} es:", options: ["4","5","6","7"], correct: 2 },
    { text: "La mediana de {3, 7, 2, 9, 5} ordenada es:", options: ["3","7","5","6"], correct: 2 },
    { text: "La varianza mide:", options: ["El valor central del conjunto de datos","La dispersión de los datos respecto a la media","La suma de todos los datos","El valor máximo menos el mínimo"], correct: 1 },
    { text: "¿Cuánto es log₂(8)?", options: ["2","4","3","16"], correct: 2 },
    { text: "Si log(x) = 2, entonces x =", options: ["20","100","2","10"], correct: 1 },
    { text: "¿Cuál es el término general de la sucesión aritmética con a₁ = 3 y diferencia d = 5?", options: ["aₙ = 5n − 2","aₙ = 3n + 5","aₙ = 5n + 3","aₙ = n + 3"], correct: 0 },
    { text: "La suma de una progresión geométrica infinita con a = 1 y r = 1/2 es:", options: ["1","3","2","∞"], correct: 2 },
    { text: "El determinante de la matriz [[2, 3], [1, 4]] es:", options: ["8","11","5","6"], correct: 2 },
    { text: "¿Cuál es la solución del sistema: x + y = 5, x − y = 1?", options: ["x = 1, y = 4","x = 4, y = 1","x = 3, y = 2","x = 2, y = 3"], correct: 2 },
    { text: "La distancia entre los puntos (1, 2) y (4, 6) es:", options: ["5","7","25","3"], correct: 0 },
    { text: "La ecuación de una circunferencia con centro (0,0) y radio 5 es:", options: ["x² + y² = 25","x² + y² = 5","x + y = 25","(x+y)² = 25"], correct: 0 },
    { text: "La pendiente de la recta que pasa por (1, 2) y (3, 8) es:", options: ["3","2","4","6"], correct: 0 },
    { text: "Una parábola de ecuación y = ax² + bx + c tiene su vértice en x =", options: ["−b/a","−b/(2a)","b/(2a)","a/b"], correct: 1 },
    { text: "El binomio de Newton para (a + b)² es:", options: ["a² + b²","a² + 2ab + b²","2a + 2b","a² − 2ab + b²"], correct: 1 },
    { text: "¿Cuánto es i² donde i = √−1?", options: ["1","−1","i","0"], correct: 1 },
    { text: "La derivada de f(x) = eˣ es:", options: ["eˣ⁻¹","xeˣ","eˣ","1/eˣ"], correct: 2 },
    { text: "La derivada de f(x) = ln(x) es:", options: ["ln(x)/x","1/x","x · ln(x)","eˣ"], correct: 1 },
    { text: "¿Cuánto vale lím(x→0) de sen(x)/x?", options: ["0","∞","1","Indefinido"], correct: 2 },
    { text: "¿Cuántos diagonales tiene un hexágono?", options: ["6","9","12","15"], correct: 1 },
    { text: "La suma de los ángulos interiores de un polígono de n lados es:", options: ["(n − 2) × 180°","n × 180°","(n − 1) × 90°","n × 90°"], correct: 0 },
    { text: "El volumen de una esfera de radio r es:", options: ["4πr²","(4/3)πr³","2πr³","πr³"], correct: 1 },
    { text: "El área lateral de un cilindro de radio r y altura h es:", options: ["πr²h","2πr + 2h","2πrh","πrh"], correct: 2 },
    { text: "Si f(x) = x³, ¿cuál es el punto de inflexión?", options: ["x = 1","x = −1","x = 0","No tiene"], correct: 2 },
    { text: "La regla de L'Hôpital se aplica cuando una límite tiene la forma:", options: ["∞ × 0","0/1 o 1/∞","0/0 o ∞/∞","0⁰"], correct: 2 }
  ]
};
