window.QUESTION_BANKS = window.QUESTION_BANKS || {};
window.QUESTION_BANKS["quimica"] = {
  label: "Química", icon: "⚗️",
  questions: [
    { text: "¿Cuál es el símbolo químico del sodio?", options: ["Na","So","S","Ni"], correct: 0 },
    { text: "¿Qué grupo de la tabla periódica contiene los metales alcalinos?", options: ["Grupo 1","Grupo 2","Grupo 17","Grupo 18"], correct: 0 },
    { text: "¿Cuál es el número atómico del carbono?", options: ["6","12","8","4"], correct: 0 },
    { text: "Los elementos del Grupo 18 son llamados gases nobles porque:", options: ["Tienen la capa de valencia completa y son muy poco reactivos","Son los más reactivos de la tabla","Forman fácilmente enlaces iónicos","Solo existen en estado líquido"], correct: 0 },
    { text: "¿Qué tipo de enlace se forma entre Na y Cl en la sal de mesa (NaCl)?", options: ["Enlace iónico","Enlace covalente","Enlace metálico","Enlace de hidrógeno"], correct: 0 },
    { text: "¿Cuántos electrones comparte cada átomo en un enlace covalente doble?", options: ["2 pares (4 electrones en total)","1 par (2 electrones)","3 pares (6 electrones)","4 pares (8 electrones)"], correct: 0 },
    { text: "Balancea: H₂ + O₂ → H₂O. ¿Cuál es la ecuación balanceada?", options: ["2H₂ + O₂ → 2H₂O","H₂ + O₂ → H₂O","H₂ + 2O₂ → 2H₂O","4H₂ + O₂ → 4H₂O"], correct: 0 },
    { text: "Una reacción exotérmica es aquella que:", options: ["Libera energía al ambiente","Absorbe energía del ambiente","No involucra cambio de energía","Solo ocurre a altas temperaturas"], correct: 0 },
    { text: "En una reacción de neutralización, un ácido reacciona con una base para producir:", options: ["Sal y agua","Solo agua","Solo sal","Gas y calor"], correct: 0 },
    { text: "¿Cuántas partículas contiene 1 mol de una sustancia?", options: ["6.022 × 10²³","6.022 × 10²²","1.602 × 10⁻¹⁹","3.011 × 10²³"], correct: 0 },
    { text: "La masa molar del CO₂ es: (C=12, O=16)", options: ["44 g/mol","28 g/mol","32 g/mol","40 g/mol"], correct: 0 },
    { text: "¿Qué pH corresponde a una solución neutra a 25 °C?", options: ["7","0","14","5"], correct: 0 },
    { text: "Una solución con pH = 3 es:", options: ["Ácida","Básica","Neutra","Alcalina"], correct: 0 },
    { text: "¿Cuál de estas es una propiedad química de la materia?", options: ["Inflamabilidad","Densidad","Punto de fusión","Color"], correct: 0 },
    { text: "La destilación es un método de separación que se basa en diferencias de:", options: ["Punto de ebullición","Densidad","Solubilidad","Tamaño de partículas"], correct: 0 },
    { text: "¿Cuál es la fórmula del ácido sulfúrico?", options: ["HCl","H₂SO₃","H₂SO₄","H₂S"], correct: 2 },
    { text: "¿Cuántos electrones tiene el elemento nitrógeno (Z=7) en su último nivel de energía?", options: ["2","3","5","7"], correct: 2 },
    { text: "El principio de Aufbau establece que los electrones llenan los orbitales:", options: ["De mayor a menor energía","De menor a mayor energía","Al azar, sin orden definido","Solo en orbitales s y p"], correct: 1 },
    { text: "¿Cuál de estas sustancias es un hidrocarburo saturado (alcano)?", options: ["Eteno (C₂H₄)","Benceno (C₆H₆)","Etano (C₂H₆)","Etino (C₂H₂)"], correct: 2 },
    { text: "La fórmula general de los alcanos es:", options: ["CₙH₂ₙ","CₙH₂ₙ₋₂","CₙH₂ₙ₊₂","CₙHₙ"], correct: 2 },
    { text: "¿Cuál es el grupo funcional de los alcoholes?", options: ["−COOH","−CHO","−OH","−NH₂"], correct: 2 },
    { text: "¿Cuál es el grupo funcional de los ácidos carboxílicos?", options: ["−OH","−CHO","−NH₂","−COOH"], correct: 3 },
    { text: "La reacción de saponificación produce:", options: ["Jabón y glicerol a partir de grasas e hidróxidos","Ácidos grasos libres y agua","Ésteres a partir de ácidos y alcoholes","Proteínas a partir de aminoácidos"], correct: 0 },
    { text: "En una reacción redox, la oxidación implica:", options: ["Ganancia de electrones","Pérdida de electrones","Ganancia de protones","Pérdida de masa"], correct: 1 },
    { text: "En una reacción redox, el agente oxidante:", options: ["Se oxida y pierde electrones","Se reduce y gana electrones","No cambia su estado de oxidación","Siempre es un metal"], correct: 1 },
    { text: "La Ley de Hess establece que la entalpía de una reacción:", options: ["Depende del camino seguido","Es independiente del camino y solo depende de los estados inicial y final","Es siempre negativa","Es siempre positiva"], correct: 1 },
    { text: "¿Qué indica el signo negativo en ΔH de una reacción?", options: ["La reacción es endotérmica","La reacción es exotérmica","La reacción no es espontánea","El sistema absorbe calor del entorno"], correct: 1 },
    { text: "El segundo principio de la termodinámica relacionado con la entropía establece:", options: ["La energía se conserva en procesos aislados","En procesos espontáneos la entropía total del universo aumenta","La entropía de un cristal perfecto es cero a 0 K","La entalpía determina la espontaneidad"], correct: 1 },
    { text: "La velocidad de una reacción química puede aumentarse:", options: ["Disminuyendo la temperatura","Añadiendo un inhibidor","Aumentando la concentración de reactivos o la temperatura","Reduciendo la presión siempre"], correct: 2 },
    { text: "Un catalizador:", options: ["Se consume durante la reacción","Aumenta la velocidad sin consumirse, bajando la energía de activación","Aumenta la energía de activación","Solo funciona en reacciones exotérmicas"], correct: 1 },
    { text: "El principio de Le Chatelier establece que si un sistema en equilibrio es perturbado:", options: ["El equilibrio no cambia nunca","El sistema se desplaza para contrarrestar la perturbación","La reacción se detiene","La constante de equilibrio cambia"], correct: 1 },
    { text: "¿Cuál es la expresión de la constante de equilibrio Kc para: aA + bB ⇌ cC + dD?", options: ["Kc = [C]^c[D]^d / [A]^a[B]^b","Kc = [A]^a[B]^b / [C]^c[D]^d","Kc = [C]·[D] / [A]·[B]","Kc = c·d / a·b"], correct: 0 },
    { text: "La molaridad (M) de una solución se define como:", options: ["Moles de soluto por litro de solución","Gramos de soluto por litro de disolvente","Moles de soluto por kilogramo de disolvente","Gramos de soluto por 100 g de solución"], correct: 0 },
    { text: "¿Cuántos moles de NaOH hay en 200 mL de solución 2 M?", options: ["0.4 mol","4 mol","0.1 mol","2 mol"], correct: 0 },
    { text: "La presión osmótica es una propiedad coligativa que depende de:", options: ["La naturaleza química del soluto","La concentración de partículas de soluto en la solución","La temperatura únicamente","El color de la solución"], correct: 1 },
    { text: "¿Cuál de estas propiedades NO es una propiedad coligativa?", options: ["Descenso crioscópico","Ascenso ebullioscópico","Presión osmótica","Viscosidad"], correct: 3 },
    { text: "En electroquímica, el ánodo es el electrodo donde ocurre:", options: ["La reducción","La oxidación","El depósito de metal","El flujo de aniones desde el exterior"], correct: 1 },
    { text: "La electronegatividad mide:", options: ["La facilidad de un átomo para perder electrones","La tendencia de un átomo para atraer electrones hacia sí en un enlace","El número de electrones de valencia","La energía de ionización del primer electrón"], correct: 1 },
    { text: "¿Cuál de estos elementos tiene mayor electronegatividad?", options: ["Cesio (Cs)","Sodio (Na)","Flúor (F)","Cloro (Cl)"], correct: 2 },
    { text: "El enlace de hidrógeno se forma entre:", options: ["Cualquier átomo de hidrógeno y cualquier otro átomo","H unido a F, O o N con otro átomo electronegativo de F, O o N","Dos átomos de hidrógeno","Hidrógeno y metales alcalinos"], correct: 1 },
    { text: "¿Cuál es el producto principal de la fermentación alcohólica?", options: ["Ácido láctico y CO₂","Etanol y CO₂","Acetona y agua","Ácido acético y H₂"], correct: 1 },
    { text: "La isomería ocurre cuando dos compuestos tienen:", options: ["La misma fórmula molecular pero diferente estructura","Diferente fórmula molecular y misma estructura","El mismo número de carbonos y diferente masa molar","La misma estructura y diferente fórmula molecular"], correct: 0 },
    { text: "¿Cuántos gramos de agua (M=18 g/mol) hay en 2 moles?", options: ["9 g","18 g","36 g","72 g"], correct: 2 },
    { text: "El pH de una solución con [H⁺] = 10⁻⁴ M es:", options: ["4","−4","10","0.0001"], correct: 0 },
    { text: "¿Cuál es la configuración electrónica del oxígeno (Z=8)?", options: ["1s² 2s² 2p⁴","1s² 2s² 2p⁶","1s² 2s⁴ 2p²","1s⁴ 2s² 2p²"], correct: 0 },
    { text: "Las fuerzas de Van der Waals son:", options: ["Fuerzas covalentes muy fuertes","Interacciones intermoleculares débiles debidas a dipolos temporales","Fuerzas iónicas entre cationes y aniones","Enlaces de hidrógeno específicos"], correct: 1 },
    { text: "En la nomenclatura IUPAC, el prefijo 'di-' indica:", options: ["1 átomo del elemento","2 átomos del elemento","3 átomos del elemento","4 átomos del elemento"], correct: 1 },
    { text: "¿Qué gas se produce en la reacción entre un metal activo como el zinc y un ácido clorhídrico?", options: ["Cloro (Cl₂)","Oxígeno (O₂)","Hidrógeno (H₂)","Dióxido de carbono (CO₂)"], correct: 2 },
    { text: "La cromatografía separa mezclas basándose en:", options: ["Diferencias de punto de ebullición","Las diferentes afinidades de los componentes por una fase estacionaria y una móvil","El tamaño de las partículas únicamente","La densidad de cada componente"], correct: 1 },
    { text: "¿Cuál es el reactivo de Tollens y para qué se usa?", options: ["Solución de KMnO₄ para detectar alquenos","Solución de [Ag(NH₃)₂]⁺ para identificar aldehídos (da espejo de plata)","Solución de Fehling para detectar cetonas","Ácido de Lucas para diferenciar alcoholes"], correct: 1 }
  ]
};
